version: '3'
services:
  syncer:
    image: embereon/syncer
    environment:
    - BALENA_DEVICE_UUID=raspi4test
    volumes:
    - ./player/main-node/led-main/data:/data
    network_mode: host
    privileged: true
    restart: always
  beacon:
    image: embereon/beacon
    network_mode: host
    privileged: true
    restart: always
  watchtower: 
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --debug --interval 30

# Add login credentials for the account in the .docker/config.json file.